#+title: Forum Ideas
* @Nyeti
** here
  OK, let's throw some ideas around within the framework of a data panel. It's not meant to be definitive but a suggestion of where we should go. Text in italics is especially tentative.

Overview
Definition: Young Archailect Empire
Symbol: the cool swirly purple logo?
Ruling archailects: four S5 Princes including Prince Vatsceh
Archailect ethos: we've not got this quite figured out yet, but creating a harmonious Terragen-xeno hybrid civilisation seems to be part of it, as does fighting the Amalgamation. Prince Vatsceh at least seems pretty interventionist.
Founding history
Origin: Mixed Terragen, Muuh, and Soft Ones. Presumably based on settlement of the Perseus Rift and Perseus Arm, which could not have happened before the 9th millennium.
Founding events: 8400s Prince Vatsceh ascends to S5; 8750 first encounter with the Amalgamation; 9012 Pluton converted for habitation; 9583-9949 Epp War; 10002 local wormhole nexus reaches 15 stars
Culture, Art, and Society
Cultural Ethos: presumably communitarian, xenophilic, possibly militaristic?
Society: this is pretty open, but could include the goal of building a great community. Maybe tribeminds are an important part of this
Intertoposophic Relations: this is where Fractalism is most important - each toposophic is expected to have a relationship with those above and below
Religion and Ideology: Fractalism is presumably part of this but can't be the only one
Ontology: no idea
Demographics
Morphodynamics: no idea
Population Breakdown: presumably mostly modosophont, but there must be some ascensions, and there are clearly a good number of S4 lesser Princes. maybe animins play a part?
Galactography
Current Territory: An irregular volume in the Perseus Periphery.
Number of Aligned Star Systems: could be anything from a hundred thousand to maybe two million
Breakdown: not much idea here - how centralised is it? Does it have a lot of loosely affiliated systems compared to "core" systems? That does seem likely given its involvement in PADO
Capital: not sure - it could be in the Pluton system though, which is important for both modosophonts and for Vatsceh's grand designs
Major Systems and Megastructures: Pluton is significant,  and Pehhpepep are
Government and Administration
Government: Imperial Administration: ?
Local/Regional Administration: ?
Administrative Divisions: ?
Citizenship: ?
Sophont Rights: presumably very good, with an emphasis on responsibility for lower toposophics
Empire Holidays: ?
Activities and Infrastructure
Civil Infrastructure: includes a local wormhole nexus and presumably also beamriders, lightwars, etc.  Settlement seems to include plenty of cold planets and moons suitable for Muuh and Soft Ones.
Economy and Activities: apparently settlement of new systems and building up infrastructure is significant. Godtech is in use.
Military Infrastructure and Warfare: Higher than usual for the Sephirotics given its involvement in PADO, which requires at least S1 intelligence to fight effectively. There also seem to be enough small polities in the Perseus Rift to justify having a modosophont military.
Interstellar Politics
Treaty Participation: Tragadi Accords and PADO plus others - what are these?  They seem to involve some kind of accommodation with the Panvirtuality.
Interstellar Relations: Generally good. The Persus Princes are allied with the Solar Dominion and Metasoft in PADO, and on good terms with the other Sephirotics. They are also have the closest relations of any major polity with the Muuh and Soft Ones, and (at least at higher toposophic levels) have made agreements with the Solipsist Panvirtuality.
Interstellar Disputes: Aside from

* @Rakuen07
** opinion on subsophont citizenship
While all sophonts are citizens, there could be disagreements on where (below the S0 grade) the "minimum intellect for citizenship" line should be. Should dogs be citizens? Monkeys? Dolphins? That a-life you just created on your virch? I expect that the answers are as diverse as the Perseus Princes polities.
** info
Okay, some information that might help us flesh out the Perseus Princes:
Distance between SolSys and the Perseus Arm: My quick look at Wikipedia says that the Perseus Arm is about 6400 light years away from the Sun. According to the first picture of the Terragen Expansion article, this distance is between the maximum range covered (from Sol Sys) by Displacement Drives and Reactionless Drives by the Current Era without the aid of xenosophont-made wormholes. Most likely, the Perseus Arm per se is sparsely colonized by the Current Era, maybe possibly seen as potentially highly valuable interstellar real estate.
The Perseus Rift: It is defined in the EG as: "Colloquial term for the volume between the Orion and Perseus arms; a vast and ill-defined volume rimwards of the Solar Dominion and Metasoft." I agree that the Perseus Princes should appear here, especially since we haven't defined how big the volume is, nor how close it is from SolSys.
Early Days of the Perseus Rift:
Perseus Rift article: "The Perseus Rift has always been a remote and troublesome region for the inner powers, and after the Version War a number of independent mainly ex-Dominion interstellar powers have emerged."
Also from the same article: "A number of exploration-dedicated archai have transcended to become full archailects, and style themselves the Perseus Princes; " Should be transapients instead of archai there?
Age of Evaluation article (5400-5800AT): "But while the Solar Dominion might be unsuccessfully trying to regain the Perseus Arm, the Negentropy Alliance is growing through the TrueModel, new polities and powers appear in the Serpens and Carina regions."
Also from the Age of Evaluation article: "5699 - Cambyses, a dry xerogaian world discovered in the Perseus rift (see Marsupial Lion)."
First Mentions of the Perseus Princes in the Timeline: In the timeline, the first mention of the Perseus Princes are from the Age of the Separate Empires (5800-6700AT). The mention is:
"Almost as a response to the disintegration of the old ComEmp a new generation of AI gods appears. These "children" of the Archailects set out to manage different regions with more autonomy. The Perseus Arm princes are merely the best known of these."


So, here's some ideas for their early history:

The Perseus Rift is reached by several parties, most notably Metasoft and the Solar Dominion long-range colony missions backed by their respective archailects.
(4445 AT - 4650 AT): The Version War happens and unfortunately Metasoft and the Solar Dominion are enemies in this conflict. Somehow, both empires lose control of the colonies.
(4650 AT - 5400 AT): The Perseus Rift and the polities within develop on their own. Panvirtuality AIs may begin to install themselves in some stars at this era too?
(5400 AT - 5800 AT): The Solar Dominion recontacts their colonies in the Perseus Rift, but they refuse to rejoin their parent Sephirotic Empire. It is clear that they are thriving without their parent Sephirotics and keep developing on their own.
(6000s AT? 6500s AT?): The first SI:4 archailects in the region emerge and style themselves Princes (or Princesses too). These archailects unite their native civilizations into the Perceus Princes archailect empire, finding common ground with each other and with the Panvirtuality. Exploration and colonization efforts towards the Perseus Arms ramp up.

* @Grawa427
- The different prince could be linked as a tribe mind, making for an S5 level tribe mind. Although we would note that term group mind would be an extreme over simplification of how the prince are linked. It would be different from how S5 normally communicate, but the princes are not one entity either, the subtlety of how their network works would be beyond the understanding of a modosophont, but the best way it has been described is that of an S5 level tribe mind.
- Also regarding the tribe minds, maybe individuals for a local tribe mind, then different tribe minds are connected into a larger tribe mind, and then maybe an even bigger tribe mind ect. Which would go well with the idea of fractalism.
- For the names, maybe "the toposophic fractal" (the first ternion), "the ruling fractal" (the second ternion, since the tribe minds are the main way of governing at different scale) and the "origin fractal" (the third ternion)
- For the third ternion/origin fractal, maybe the Perseus prince are trying to gather as many different clades and type of virtual as possible. So it isn't merely about having many xenosophonts, but having a large diversity of origin. The origin of the terragen sphere would lead to the origin of many clades, which would lead to the origin of many subclade ect. Same idea for the Muuh volume ect. This would make for the aesthetic of a fractal of origins, and hence fractalism.

  For fractalism it could 3 core ternion with Prince Vatsceh representing them all and the 3 other prince specialising in one of them.

First core ternion :
- Deep intertoposophic connections : each higher toposophic level are advised to merge with lower toposophic beings, and after some point they are advised to separate from them and merge with another lower toposophic being. (I am bad for names, but someone else can try to come up with a cool name)

Second core ternion :
- Deep connections between individuals : individuals inside the same toposophic level should form group minds. Tribe minds would be the most common form of government in the Perseus Prince.

Third core ternion :
- Deep connections between sphere of origin : the Perseus Prince is trying to connect with xenosophont empires, and as such has large part of it dedicated to xenosophont (muuh, soft ones and maybe in lower amount others like tohul etc). An idea concerning this is that there might be significantly more effort made by transapient to help xenosophonts ascend than terragens (maybe not the Muuh since it doesn't seem like something they would do, but what about a community of S1 soft ones). This might be because there are a much higher number of ascended terragen than xenosophont in the terragen sphere. There might also be a large amount of population that are xenosplice or xenoprovolve.

* @Cogs13
- I think that there could be even a bit more emphasis on military expenditure, and particularly on communications screening. I think the military expenditure could be so high in the region that it could cause delays in delivering non-military goods to inhabitants. Post scarcity is mostly unviolated, but on occasion local auto-war surges may cause minor short-term shortages.
- Also, there may be slight accumulating latency delays since communications around amalgamation border territory would need to be more heavily screened for viruses.
- The autowar surges could be part of a greater strategy to deter the amalgamation by matching force numbers at different locations on a continuous basis. These surges don't really fight, but merely are present to show readiness. Tourists and enthusiasts might even be nearby to watch their transits, since there is an unsually high population of them. There also might be a more stringent wormhole quarantine program, which might be switched on very rarely, but has happened a few times over the centuries.
- Lastly, I think with the tribe minds there may be some vulnerabilities with regards to subversion. It would seem that there might need to be protocals in place to make sure that tribes don't let themselves subverted one by one(Divided and conquered). (Or perhaps tribe minds are actually less vulnerable, due to compartmentalization)
