#+title: Ideas That I Got From Nyeti's Doc
- here is also some ideas that @Nyeti came up with in his google doc that he shared with me
  - xenophilia could be one of the Perseus Prince's values
  - of course they need energy for new wormhole links - they are a buorgening empire. I think this has interesting implications! Perhaps they ask for energy from other empires?
  - they have good relations with Metasoft, the Solar Dominion (even those those two were enemies in the Version War lol), and all
  - they have bad relations with the Amalgamation, but it has bad relations with everyone.
  - of course, @Nyeti followed my proposed questions and categories in fleshing. perhaps they are good for something after all!
  - I also want to flesh out what they DON'T value, or frown upon (perhaps solipsism since they are a tight-knit community)
  - what are they working towards? archai motives are incomprehensible, but what are modo societies in here trying to do
  - perhaps consult stevebowers? he expanded it after all

- @Nyeti: I quite like the idea that, with all this, there's a bit of a mythic feel to the place. A court of powerful Princes, legend and history blending, new worlds of extreme diversity, and the threat of the Amalgamation beyond. Perhaps that's their memetic appeal: adventure and legend on the high frontier.
