#+title: Research Notes
* notes on the Perseus Princes
[2025-04-24 বৃহঃ 14:31]
** Pluton Volume
- It was the Muuh that first colonized it. Prior to Terragen Contact, most of its resources went unused.
- the Epp are a subclade of the Soft Ones
- during the 8400s A.T, the Archai Prince Vatsech ascended to SI:5
- the Perseus Princes are a hybrid civilization with the Soft Ones, Terragens, and Muuh
- after the Nargonn attack and busting of rebel terrorist systems, transapient Epp-Hepeph hiveminds and any Soft One Trillienists were reprogrammed and rejoined the Perseus Prince's Empire.
- Vatsech seems to be overseeing the interaction between the Terragens, Soft Ones and Muuh and interfereing when needed to bring about their best qualities and promote the creation of a truly constructive hybrid terragen-xenosophont cluster.
** The Perseus Rift
- a number of exploration-dedicated archai have transcended to become full archai and style themselves the Perseus Princes
** Fractalism
- Prince Vatsceh sponsors Fractalism, a developed form of Buddhism informed by some beliefs of the ancient Muuh.
- Fractalists believe that there are gods in adjacent brains, similar to the Great Archai of our own world.
- in constrant, Trillennialist beliefs are an offshoot of the Omegists who believed that entropy would spontaneously reverse itself after a trillion years and all they had to do was cool the stars and themselves down to near absolute zero in order to survive the interim period. Waiting for the Trillenium, many Trillinarians have relocated to long-lived red dwarf stars.

* notes on the Solipsist Panvirtuallity
[2025-04-24 বৃহঃ 14:46]
- the name of the governing S6 archai is not known
- large but unknown number of first toposophic or higher transapients.
- this is interested in exploring virtual realities and abstract spaces.
- Ordinary sophonts cannot reliably predict whether they will be allowed to enter an area or allowed to leave it.
- they are the main rival to the Sephirotics
