#+title: Fourth Draft
* introduction
The Perseus Princes is a rapidly expanding archailect-led empire in the Outer Volumes based on Fractalism: a philosophy that sees society as a fractal of beings extending below the smallest scales of space and above the highest archailects with responsibility for all. The Perseus Princes are eager to grow the fractal in richness, and thus have integrated the local Muuh and Soft Ones in the region.
* history
The first polities of the Perseus Princes took root during the Version War as settlers, mostly colonists loyal to either the Solar Dominion or Metasoft, settled the region. While scholars disagree on the dates - partly due to incomplete records and partly to competing definitions of the Rift's boundary - they agree that Terragens entered the Rift as conflict broke out in the Inner Sphere. Located hundreds of light-years away from the nearest wormhole, these colonies soon lost contact with their parent empires. Even though space and resources were plentiful, Metasoft's and the Dominion's colonies distrusted each other, separated by ideological divisions and mutual enmity. In this environment, independent settlers would inevetably go their own way.

Unlike the situation during the founding of the Red Star M'pire, no single transapient held overwhelming dominance over the others during the development of the Perseus Rift. The most advanced minds to arrive among the first settlers were seven SI:2 individuals divided into two opposing blocs: four aligned with Metasoft, and three loyal to the Dominion. Fortunately, their colonies were scattered across distances of tens of light-years, which appears to be a main reason why open interstellar warfare never occurred.

Instead, the Metasoft-Dominion conflict in the Rift mainly played out by means of digital and information warfare, propaganda, a technological and toposophic arms race aimed at creating an aligned Third Singularity transapient, and occasional proxy wars. Meanwhile, independent colonies led by modosophonts or SI:1s sought to maneuver carefully amid the conflicts of the major powers in order to profit and grow.

This was facilitated by the fact that even most developed Metasoft and Dominion colonies weren't able to efficiently exert power in distant systems because of light-speed lags, logistical challenges and acts of sabotage from their rivals. As a result, they couldn't suppress the emergence of new SI:2 entities unaligned with either Sephirotic, and had to become one among many local interstellar hegemons confined to their respective zones of influence.

[b][b][b]Over time, even these Sephirotic colonies grew distant from their common root, moving on from their grudges and gradually developing into culturally and ideologically distinct offshoots of their parent empires. In the 4700s AT, the Panvirtuality began settling marginal systems that were largely ignored by most factions, developing and expanding their presence in the following centuries.

By the 5000s AT, the Perseus Rift had evolved into a multipolar frontier dominated by a small number of major polities led by the local SI:3 entities, linked with each other and the numerous minor polities in a dynamic web of alliances and rivalries. [/b][/b][/b]The first effort to revert the Rift colonies under the influence of the Sephirotic Empires was in the 55th century when diplomatic and religious missions from the Dominion made contact, but the colonies had diverged to the point that few wanted to rejoin.

By 6500 AT one alliance of godlings had ascended to a collective of SI:4 archailects ruling a modest empire and directing expansion rimwards. They established friendly relations with the neighbouring Solar Dominion and Metasoft, and cemented local agreements with the Panvirtuality for sharing resources that they had been developing.

The frontier continued to expand. The vanguard - the famous “light speed frontier” - was increasingly made up of archailect's avatars and servants equipped with reactionless drive ships. Stars were now being linked into a growing sector of the Wormhole Nexus under the archailects control. They established bases and empires, uniting the disparate local polities with their own followers, and over the next few centuries they formed an alliance and styled themselves the Perseus Princes.

The Princes rose to prominence in the 9th millennium. Four events combined to bring this about. First was the discovery of the Muuh empire in the Perseus Arm, followed by first contact with the Soft Ones in 8294. Less than 200 years later Prince Vatsceh ascended to the Fifth Toposophic. Following eir latest ascension, Prince Vatsceh established eir seat in Sierpens, distributing most of eir processing substrate through this star system and the rest of the Pluton Volume.

Then in 8750 came the first report of the Amalgamation. The Princes initially played a minor part in the defence, but the Amalgamation persisted as an existential threat, and when the Perseus Arm Defence Organisation (PADO) was formed to drive it back, the Princes supported it ardently. The empire grew to value unity in diversity not only as a virtue but also as power to oppose the Amalgamation.

The ancient alien civilisations of the Muuh and Soft Ones formed close bonds with the Perseus Princes. In 9012, Prince Vastceh opened Pluton, a local former gas giant stripped of its atmosphere, for surface habitation, and soon, the system became a cultural and economic centre for the empire.

Since then, three more Princes - Nayadara, Eguil, and Berva - have joined Vatsceh at the fifth toposophic. The Pluton Volume’s wormhole network connects three thousand stars to the Nexus proper, while new habs and worlds are settled constantly. And the Princes are steadily expanding their reach into the unsurveyed stars of the Perseus Arm and the fragmented empires of the Rift. However, expansion has almost completely stopped in the areas close to the Amalgamation Containment Region, where the Princes maintain the bulk of their military presence.

Meanwhile, many polities on the coreward borders organise more conventional militaries for wars against the smaller empires of the Rift. It is unclear why the Princes themselves allow such conflicts to continue when they could easily assimilate or wipe out most of these minor empires.s loyal to Solar Dominion and Metasoft
* Fractalism
Though Fractalism started as a religion based on Buddhism and Etodism, it also grew into an ontology that took inspiration from the traditions of the local Muuh and Metasoft concepts of cosmos and consciousness as networks.

Embracing the thinking that there are other branes besides ours, Fractalists believe that the Gods of other branes rule ours, and that this continues upwards infinitely.

Fractalism extends below modosophonts. Pets, presapient animals, bots, alifes, and even non-sentient plants are considered to be an integral part of society and may act on their own. Beings encourage each other to create new life of diverse types - technological, organic, or simulated.

Fractalism teaches beings to guide lower beings while obeying higher beings. While Solarism also teaches this, Fractalism encourages many ruling beings instead of just one. One example of this is that Vatsech has not blocked other Princes from ascending to eir level.

But the Perseus Princes are not archailectocracies and expect each toposophic level to govern or manage itself. Modosophonts may rule themselves by consensus, cyber-anarchy, and meritocracy.

To match the cognitive ability of their higher bretheren, the Princes encourage beings to form tribeminds or temporarily merge into higher beings.

New religions in the Principalities build on Fractalism, and existing religions within the region have adapted to integrate within wider society. The Princes prefer their subjects to live as an organic whole.
The Princes encourage creating new kinds of life. While some bionts are happy with neogenesis or provolving species, most sophonts release new vec and neuman designs, inspired by Metasoft's design culture. Yet more sophonts create alife, and some successful alife clades like Busard Swarms and Bliffoth's Abstract Linkers started out in Perseus Prince Virches.
* Life And Culture
Perseus art and architecture makes heavy use of fractal motifs - such as snowflakes.

Narratives are another popular artform among the Princes, very often in the form of fabulist stories that blend fact, speculation, and myth. Legendary retellings of history or dreams of the future are perennial favourites. Some commentators believe this stems from Muuh culture - but others hold that the Princes are cultivating their empire as a new mythic frontier, where everyone can find a role in the story of life, and anything is possible.
